name:                jsonpath
version:             0.1.0.0
github:              "akshaymankar/jsonpath-hs"
license:             BSD3
author:              "Akshay Mankar"
maintainer:          "itsakshaymankar@gmail.com"
copyright:           "Akshay Mankar"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/akshaymankar/jsonpath-hs#readme>

dependencies:
- aeson
- attoparsec
- base >= 4.7 && < 5
- text
- unordered-containers
- vector

library:
  source-dirs: src

tests:
  jsonpath-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson-casing
    - bytestring
    - file-embed
    - hspec
    - hspec-attoparsec
    - jsonpath-hs
